add FuelEconomy
IVISolution/vehicle_signal_specification pull request #4
Opened 2024-11-01 07:26 UTC by CoffeeMoneyMakers

add FuelEconomy

2024-11-01 07:28 UTC, CoffeeMoneyMakers commented
https://github.com/IVISolution/vehicle_signal_specification/pull/3 PR이 Merge 되지 않은 상태에서 unit: km/l를 사용하고 있기 때문에 Build Fail이 발생하고 있습니다.

2024-11-01 07:30 UTC, CoffeeMoneyMakers commented
type: actuator 일 때 unit: 단위를 2개 이상 적용 시킬 수 있는 방법이 기존 vspec에는 존재하지 않아 unit 단위를 km/l로 하였습니다.
(unit 단위를 km/l, ml/100km, l/100km, mpg 모두 적용할 수 있는 방법이 있을 지 검토가 필요한 상황입니다.)

2024-11-01 07:40 UTC, CoffeeMoneyMakers commented
기존 FuelSysten,vspec에 아래와 같이 순간 연료 소모량과 평균 연료 소모량이 정의되어 있습니다.
![image](https://github.com/user-attachments/assets/0a979cae-70fd-4bbf-8b77-b27233eeb6d5)
다만, unit의 단위가 연료 소모량을 표현하기 위한 단위가 아니라 연비를 표현하기 위한 단위여서 수정이 필요할지 검토가 필요합니다.

2024-11-15 01:55 UTC, cws55 commented
1. VSS는 2개 이상의 unit을 지정을 제공하지 않는것으로 확인됩니다. 필요한 경우 "km/h" and "m/s" 와 같이 2개의 Signal을 만드는 것을 허용 합니다.
"VSS does not offer any syntax for defining alternative units for a specific signal."
- https://github.com/COVESA/vehicle_signal_specification/blob/master/docs-* gen/content/rule_set/data_entry/data_units.md#introduction-to-data-units-in-vss
2. Unit의 경우 기본적으로 Automotive 표준을 우선 적용하며 이후 SI Unit에 대해 검토하는 것으로 보여집니다. "Following the best practices for units in VSS we should use preferably automotive standards and then SI"
- https://github.com/COVESA/vehicle_signal_specification/issues/147

2024-11-15 02:31 UTC, cws55 commented on spec/Powertrain/FuelSystem.vspec
> +  description: Current real-time fuel consumption rate. Refreshed frequently during vehicle operation.
"Current real-time"의 내용이 중복적이라 "Real-time"로만 표현하는 것은 어떤지 의견 드립니다.

2024-11-15 02:31 UTC, cws55 commented on spec/Powertrain/FuelSystem.vspec
> +  description: Average fuel economy calculated from the last refueling event to current time.
AfterRefuelingFuelEconomy Signal 뿐만 아니라 필요하다면 commect를 통해 추가 설명을 적어도 좋을것 같습니다.

2025-10-27 12:13 UTC, InsangJang-ivis commented on spec/Powertrain/FuelSystem.vspec
> +  description: Current real-time fuel consumption rate. Refreshed frequently during vehicle operation.
Real-time으로 수정하였습니다.
확인 부탁드립니다.

2025-10-27 12:14 UTC, InsangJang-ivis commented on spec/Powertrain/FuelSystem.vspec
> +  description: Average fuel economy calculated from the last refueling event to current time.
description의 내용을 좀 더 명확하게 수정하고 해당 신호에 대한 comment 내용도 추가하였습니다.
확인 부탁드립니다.

2025-10-28 02:27 UTC, cws55 requested changes
4개의 signal 모두 sensor가 적절해 보이는데 검토 부탁드립니다.
자동으로 계산되어 제공되는 값들로 생각되네요.

2025-10-28 02:27 UTC, cws55 commented on spec/Powertrain/FuelSystem.vspec
> +  description: Average fuel economy for current driving cycle, calculated from trip start to current time.
comment: The driving session typically starts when the vehicle begins moving and ends after a prolonged stop (e.g., after 10–15 minutes with zero speed) or a user-initiated reset. Does not reset on refueling by default.

위와 같은 코멘트를 추가하면 좋을 것 같은데 작성하려 했던 의도와 맞는지 확인 부탁드립니다.
문구는 참고 목적으로 확인해 보세요.

2025-10-28 02:49 UTC, summeromance commented on spec/Powertrain/FuelSystem.vspec
> +  description: Overall lifetime average fuel economy since vehicle production or last reset of historical data.
내용이 좀 극단적입니다. 마지막 reset 이후의 평균 연비임을 나타내는게 좋겠습니다. 차 생산이후부터의 연비는 조금 오버한 느낌이 있습니다.

2025-10-28 07:51 UTC, closed without merging